export const SEARCH_CITY = 'SEARCH_CITY'
export const GET_CUISINES = 'GET_CUISINES'
export const GET_RESTAURANTS = 'GET_RESTAURANTS'
export const SET_LOADING = 'SET_LOADING'
export const SET_USER = 'SET_USER'
export const REMOVE_USER = 'REMOVE_USER'